### ISSUE TITLE
RGB to HSV

### ISSUE THREAD

**Issue by pic-pick** [TaeJuneJoung/21WKU_APP#2]
https://developer.android.com/reference/android/graphics/Color#RGBToHSV(int,%20int,%20int,%20float[])

**Comment by canon11120** [comment]
android.graphics의  RGBToHSV() 메서드 확인 바랍니다.

**Comment by TaeJuneJoung** [comment]
깐부 팀입니다.

**Comment by TaeJuneJoung** [comment]
Q: ImageView로 처리하였을 때 HSV변경이 잘 이뤄지지 않습니다.

A: BitMap방식을 이용하여서 바꾼 후에 이중 for문을 처리하여 변경하여 주고 다시 변환하여 사용하면 될 것으로 봅니다.
