### ISSUE TITLE
MapView Event 감지 부분 this에서 오류가 납니다

### ISSUE THREAD

**Issue by chan091955** [TaeJuneJoung/21WKU_APP#3]
mapView.setMapViewEventListener(this);
 mapView.setPOIItemEventListener(this);

**Comment by chan091955** [comment]
https://apis.map.kakao.com/android/guide/#urlscheme_move_to_place

**Comment by TaeJuneJoung** [comment]
에비동 팀 -> `this` 부분에 들어가는 요소가 어떻게 처리되어야 하는지에 대한 질문입니다.

해당 부분은 제가 멘토링 하려고 합니다.
추후 이와 다른 의견들 있으시면 더 도와주셔도 감사하겠습니다

**Comment by TaeJuneJoung** [comment]
this에는 해당 부분이 들어가게 됩니다.

`new MapView.MapViewEventListener()`

따로 함수에 처리해서 함수명 진행하셔도 되고, 해당 부분을 넣어서 재정의(Override) 되는 부분들에 따라

필요한 부분들을 처리하셔도 됩니다.

이벤트 관련 부분도 링크가 잘 되어 있긴한데 아래에 링크를 하나 더 달아두도록 하겠습니다.

https://apis.map.kakao.com/android/documentation/
