### ISSUE TITLE
비트멥

### ISSUE THREAD

**Issue by pic-pick** [TaeJuneJoung/21WKU_APP#5]
비트맵 변환 코드

https://www.masterqna.com/android/38348/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B9%84%ED%8A%B8%EB%A7%B5-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%98%81%EC%97%AD%EB%B6%80%EB%B6%84-rgb-%EC%A2%8C%ED%91%9C%EC%B6%9C%EB%A0%A5-%ED%9B%84-%EC%83%89%EC%83%81-%EB%B3%80%ED%99%98

**Comment by TaeJuneJoung** [comment]
깐부팀.
해당 부분 소스에서 확인후 해결했습니다.

**Comment by pic-pick** [comment]
2021년 10월 30일 (토) 오후 11:15, TaeJuneJoung ***@***.***>님이 작성:
