### ISSUE TITLE
커스텀 리스트뷰

### ISSUE THREAD

**Issue by sohyemin** [TaeJuneJoung/21WKU_APP#6]

**Comment by canon11120** [comment]
https://mixup.tistory.com/46 참고바랍니다.

**Comment by canon11120** [comment]
simple 한 리스트뷰 입니다. 

https://webnautes.tistory.com/1020

**Comment by TaeJuneJoung** [comment]
각 팀들 필요에 따라 접근하여 해결하는 부분 확인했습니다.
