### ISSUE TITLE
파이어베이스 회원가입시 회원가입실패 오류 문제 발생

### ISSUE THREAD

**Issue by yoonhyesu** [TaeJuneJoung/21WKU_APP#7]
https://www.youtube.com/watch?v=xZthfQ9Elx4  유튜브링크입니다

**Comment by TaeJuneJoung** [comment]
해당 부분은 문제 없이 잘 동작하는 것을 확인했습니다.
Chrome 창이 다중으로 나와서 못 찾은 경우였습니다.
