### ISSUE TITLE
파이어베이스 파이어스토어에서 데이터를 가져오는 법

### ISSUE THREAD

**Issue by chan091955** [TaeJuneJoung/21WKU_APP#8]
열심히 해봤지만 어시스턴트도 읽고 해보았지만 한번만 도와주시면 감사하겠습니다

DocumentReference docRef = db.collection("users").document("yoguzoza");
        docRef.get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
            @Override
            public void onComplete(@NonNull Task<DocumentSnapshot> task) {
                if (task.isSuccessful()) {
                    for (QueryDocumentSnapshot document : task.getResult()) {
                        Log.d(TAG, document.getId() + " => " + document.getData());
                    }
                } else {
                    Log.w(TAG, "Error getting documents.", task.getException());
                }
            }
        });

**Comment by chan091955** [comment]
코드를 잘 못 올려서 다시 올립니다...
DocumentReference docRef = db.collection("users").document("yoguzoza");
docRef.get().addOnCompleteListener(new OnCompleteListener<DocumentSnapshot>() {
    @Override
    public void onComplete(@NonNull Task<DocumentSnapshot> task) {
        if (task.isSuccessful()) {
            DocumentSnapshot document = task.getResult();
            if (document.exists()) {
                Log.d(TAG, "DocumentSnapshot data: " + document.getData());
            } else {
                Log.d(TAG, "No such document");
            }
        } else {
            Log.d(TAG, "get failed with ", task.getException());
        }
    }
});

**Comment by chan091955** [comment]
에비동팀입니다...

**Comment by TaeJuneJoung** [comment]
`document.getData())`을 통해 가지고 오는 것을 확인하였습니다.
해당 부분을 Map으로 담아서 String, Object로 key, value 처리 되어 있어 해당 부분 고려하여 작업하시면 됩니다.

추가적인 질문으로 FCM에 질문하셔서 답변드립니다.
tools 부분에 있는 내용 확인해보시고
예제 소스로 Firebase에서 제공하고 있습니다.
https://github.com/firebase/quickstart-android/blob/7147f60451b3eeaaa05fc31208ffb67e2df73c3c/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java

tools 부분에 영어 글 읽는거 확인 잘 해보시고
조금 틀린 부분도 있는거 같으니 위의 예제 소스 확인하시면서 경로 찾아서 구조 보시고 이해하시면 원활할거 같습니다.
